### ISSUE TITLE
P2T on ImageNet-22K?

### ISSUE THREAD

**Issue by fyaft2012** [yuhuan-wu/P2T#10]
Hi @yuhuan-wu , thank you for share the code of this excellent work! Have you trained P2T on ImageNet-22K dataset or any further plan to do it? If so, could you please share the pretrained model on ImageNet-22k?

Thank you.

**Comment by yuhuan-wu** [comment]
Hi! Currently we cannot meet the experimental requirement of training P2T on ImageNet-22K. So we do not have plans on releasing P2T models pretrained on ImageNet-22K.

Best,
Yu-Huan
