### ISSUE TITLE
FPS testing

### ISSUE THREAD

**Issue by LMMMEng** [yuhuan-wu/P2T#14]
Could you please release the code for the fps testing?

**Comment by yuhuan-wu** [comment]
For the classification, we use the simple code that first runs the model for 100 steps, followed by a `torch.cuda.sychronize` function, with the batchsize=10.

For detection and segmentation tasks, we directly utilize the `test.py` of mmsegmentation and mmdetection frameworks.

**Comment by LMMMEng** [comment]
Many thanks!
