### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Wzw666888** [yuhuan-wu/P2T#3]
I am very interested in your model. Will you release the code? Thanks.

**Comment by yuhuan-wu** [comment]
Hi, I am preparing to release the code and pretrained models. Sorry and please wait in patience (WIP).

**Comment by Wzw666888** [comment]
Thank you for your efforts! When will it be released?

**Comment by Wzw666888** [comment]
Hope to get your exact time!

**Comment by yuhuan-wu** [comment]
Hi, we have almost prepared well. Some pretrained models are waiting for the approval of Alibaba.  I will release the code and some weights trained on university. Please check the newest repository, thanks!
