### ISSUE TITLE
the weights question

### ISSUE THREAD

**Issue by yjj-liwei** [yuhuan-wu/P2T#4]
Hello!

Are there pre-training weights for p2t-small and p2t-base? Can you send it to me if there is one?

Thanks you！

**Comment by yuhuan-wu** [comment]
Thanks for your attention! The corresponding pretrained weights are as below:
P2T-basev1: https://drive.google.com/file/d/1fEIMyT05a0Oj6tPdNaVxITJugg4sQKAo/view?usp=sharing
P2T-smallv1: https://drive.google.com/file/d/1_UUrrQdbAiNf4y5gZCETG23h7EYMV18O/view?usp=sharing

Note:
This paper is still under peer review. Our newer revision has achieved much better performance compared with the current released version. We will release our new P2T models of several fundemental vision tasks with better performance after the acceptance.

**Comment by yuhuan-wu** [comment]
Dear liwei,

Our paper has been accepted by IEEE TPAMI. As promised, we have release full code for training and testing. 
Please check the repository to see the updates.
Thanks again for your attention!

Best,
Yu-Huan
