### ISSUE TITLE
P2T replaces PVT trunk bug

### ISSUE THREAD

**Issue by liu-tianxiang** [yuhuan-wu/P2T#5]
When I replaced the PVT trunk with P2T in my code, I encountered an error  ：   
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [16, 512, 3, 3]], which is output 0 of AdaptiveAvgPool2DBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by yuhuan-wu** [comment]
Thanks for you notice. In some higher torch versions, inplace operation after adaptive_avg_pool is not supported.

I have disabled the inplace operation in the newest version. See the right change here: https://github.com/yuhuan-wu/P2T/blob/4d52408492514cd08fb3ba5afa1792f3a3c7054b/p2t.py#L74

**Comment by liu-tianxiang** [comment]
Thanks! problem solved
