### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by just1226** [yuhuan-wu/P2T#6]
我应该如何导入预训练好的权重到模型中？以便开始训练我的模型。

**Comment by yuhuan-wu** [comment]
Good question.
P2T has four stages, each stage outputting one feature with scale of 1/4, 1/8, 1/16, and 1/32. 
You can add these features to a list (Like: https://github.com/yuhuan-wu/P2T/blob/8f3e3b21a5742d375dc5857cce602441b8905771/segmentation/p2t.py#L304), and then you can construct a FPN/U-Net with the output of P2T backbone.

**Comment by just1226** [comment]
Thank you very much. I have solved.

**Comment by yuhuan-wu** [comment]
Good to hear that~
