### ISSUE TITLE
关于中国学生浏览google drive不便的问题

### ISSUE THREAD

**Issue by Bronya-h** [yuhuan-wu/P2T#9]
由于墙的存在，google drive在中国没有服务器，中国的学生想要下载权重和log只能找付费的翻墙软件，会造成额外的开销。您这里能将权重和log再上传到百度云盘或者阿里云盘上吗？或者其他的资料共享平台？

**Comment by yuhuan-wu** [comment]
Great advice. I have uploaded all files to BaiduPan.

Link: [https://pan.baidu.com/s/1JkE62CS9EoSTLW1M1Ajmxw?pwd=yhwu](https://pan.baidu.com/s/1JkE62CS9EoSTLW1M1Ajmxw?pwd=yhwu)
